ocupacionhabitacion:
    resource: "@LIHotelBundle/Resources/config/routing/ocupacionhabitacion.yml"
    prefix:   /admin/ocupacionhabitacion

li_hotel_usuario:
    resource: "@LIHotelBundle/Resources/config/routing/usuario.yml"
    prefix:   /admin/usuarios

li_hotel_factura:
    resource: "@LIHotelBundle/Resources/config/routing/factura.yml"
    prefix:   /factura

li_hotel_compensacion:
    resource: "@LIHotelBundle/Resources/config/routing/compensacion.yml"
    prefix:   /admin/compensacion

li_hotel_reserva:
    resource: "@LIHotelBundle/Resources/config/routing/reserva.yml"
    prefix:   admin/reservas

li_hotel_reserva_user:
    resource: "@LIHotelBundle/Resources/config/routing/reserva.yml"
    prefix:   user-admin/reservas

li_hotel_bebida:
    resource: "@LIHotelBundle/Resources/config/routing/bebida.yml"
    prefix:   /admin/bebidas

li_hotel_llamada:
    resource: "@LIHotelBundle/Resources/config/routing/llamada.yml"
    prefix:   /admin/llamadas

li_hotel_categoriahabitacion:
    resource: "@LIHotelBundle/Resources/config/routing/categoriahabitacion.yml"
    prefix:   /admin/categoriahabitacion

li_hotel_tipohabitacion:
    resource: "@LIHotelBundle/Resources/config/routing/tipohabitacion.yml"
    prefix:   /admin/tipohabitacion

li_hotel_tipo:
    resource: "@LIHotelBundle/Resources/config/routing/tipo.yml"
    prefix:   /admin/tipo

li_hotel_habitacion:
    resource: "@LIHotelBundle/Resources/config/routing/habitacion.yml"
    prefix:   /habitaciones

LIHotelBundle_homepage:
    path:  /
    defaults: { _controller: LIHotelBundle:Inicio:index }
    requirements:
        methods:  GET

LIHotelBundle_inicio:
    path:  /inicio
    defaults: { _controller: LIHotelBundle:Inicio:indexUser }
    requirements:
        methods:  GET

LIHotelBundle_consultar:
    path:  /consultar
    defaults: { _controller: LIHotelBundle:Inicio:consultar }
    requirements:
        methods:  GET

LIHotelBundle_registro:
    path:  /registro
    defaults: { _controller: LIHotelBundle:Inicio:registro }
    requirements:
        methods:  GET|POST

LIHotelBundle_registro_admin:
    path:  /registroAdmin
    defaults: { _controller: LIHotelBundle:Inicio:registro_admin }
    requirements:
        methods:  GET|POST

_admin:
    path:  /administrativo
    defaults: { _controller: LIHotelBundle:Inicio:admin }
    requirements:
        methods:  GET

_user:
    path:  /user-admin
    defaults: { _controller: LIHotelBundle:Inicio:user }
    requirements:
        methods:  GET

reporte_diario:
    path:  /reporte-diario
    defaults: { _controller: LIHotelBundle:Inicio:reporteDiario }

user_consumos:
    path:  /consumos
    defaults: { _controller: LIHotelBundle:Reserva:consumos }