<?php

namespace Proxies\__CG__\LI\Bundle\HotelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tipo extends \LI\Bundle\HotelBundle\Entity\Tipo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'LI\\Bundle\\HotelBundle\\Entity\\Tipo' . "\0" . 'id', '' . "\0" . 'LI\\Bundle\\HotelBundle\\Entity\\Tipo' . "\0" . 'tipoHabitacion', '' . "\0" . 'LI\\Bundle\\HotelBundle\\Entity\\Tipo' . "\0" . 'categoriaHabitacion', '' . "\0" . 'LI\\Bundle\\HotelBundle\\Entity\\Tipo' . "\0" . 'precio', '' . "\0" . 'LI\\Bundle\\HotelBundle\\Entity\\Tipo' . "\0" . 'espacioInterno', '' . "\0" . 'LI\\Bundle\\HotelBundle\\Entity\\Tipo' . "\0" . 'servicios', '' . "\0" . 'LI\\Bundle\\HotelBundle\\Entity\\Tipo' . "\0" . 'bebidasMinibar');
        }

        return array('__isInitialized__', '' . "\0" . 'LI\\Bundle\\HotelBundle\\Entity\\Tipo' . "\0" . 'id', '' . "\0" . 'LI\\Bundle\\HotelBundle\\Entity\\Tipo' . "\0" . 'tipoHabitacion', '' . "\0" . 'LI\\Bundle\\HotelBundle\\Entity\\Tipo' . "\0" . 'categoriaHabitacion', '' . "\0" . 'LI\\Bundle\\HotelBundle\\Entity\\Tipo' . "\0" . 'precio', '' . "\0" . 'LI\\Bundle\\HotelBundle\\Entity\\Tipo' . "\0" . 'espacioInterno', '' . "\0" . 'LI\\Bundle\\HotelBundle\\Entity\\Tipo' . "\0" . 'servicios', '' . "\0" . 'LI\\Bundle\\HotelBundle\\Entity\\Tipo' . "\0" . 'bebidasMinibar');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tipo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoHabitacion($tipoHabitacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoHabitacion', array($tipoHabitacion));

        return parent::setTipoHabitacion($tipoHabitacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoHabitacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoHabitacion', array());

        return parent::getTipoHabitacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoriaHabitacion($categoriaHabitacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoriaHabitacion', array($categoriaHabitacion));

        return parent::setCategoriaHabitacion($categoriaHabitacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoriaHabitacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoriaHabitacion', array());

        return parent::getCategoriaHabitacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio($precio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', array($precio));

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', array());

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setEspacioInterno($espacioInterno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspacioInterno', array($espacioInterno));

        return parent::setEspacioInterno($espacioInterno);
    }

    /**
     * {@inheritDoc}
     */
    public function getEspacioInterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEspacioInterno', array());

        return parent::getEspacioInterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setServicios($servicios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServicios', array($servicios));

        return parent::setServicios($servicios);
    }

    /**
     * {@inheritDoc}
     */
    public function getServicios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServicios', array());

        return parent::getServicios();
    }

    /**
     * {@inheritDoc}
     */
    public function setBebidasMinibar($bebidasMinibar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBebidasMinibar', array($bebidasMinibar));

        return parent::setBebidasMinibar($bebidasMinibar);
    }

    /**
     * {@inheritDoc}
     */
    public function getBebidasMinibar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBebidasMinibar', array());

        return parent::getBebidasMinibar();
    }

    /**
     * {@inheritDoc}
     */
    public function addBebidasMinibar(\LI\Bundle\HotelBundle\Entity\Bebida $bebidasMinibar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBebidasMinibar', array($bebidasMinibar));

        return parent::addBebidasMinibar($bebidasMinibar);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBebidasMinibar(\LI\Bundle\HotelBundle\Entity\Bebida $bebidasMinibar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBebidasMinibar', array($bebidasMinibar));

        return parent::removeBebidasMinibar($bebidasMinibar);
    }

}
