<?php

namespace LI\Bundle\HotelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BebidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BebidaRepository extends EntityRepository
{
	public function portipo_id($id){
		$query = $this->getEntityManager()
				->createQuery('SELECT u 
				FROM LIHotelBundle:Bebida u 
				WHERE u.tipoHabitacion = :tipo_id');
		$query->setParameter('tipo_id', $id);
		$result = $query->getResult();
        
        return $result;
	}
}
