<?php

namespace LI\Bundle\HotelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginRepository extends EntityRepository
{
	public function validarCuenta($m, $p){
        /*$qb = $this->getEntityManager()
           ->createQuery('
                SELECT b
                FROM LIHotelBundle:Usuario b
                WHERE b.mail = :mail AND b.clave = :pass
            ')
            ->setParameter("mail", $m)
            ->setParameter("pass", $p)
            ->getResult();*/

		$query = $this->getEntityManager()
				->createQuery('SELECT u 
				FROM LIHotelBundle:Usuario u 
				WHERE u.mail = :mail AND u.clave = :pass');
		$query->setParameter('mail', $m);
		$query->setParameter('pass', $p);
		$user = $query->getResult();
        
        return $user;
	}
}
