<?php

namespace LI\Bundle\HotelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OcupacionHabitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OcupacionHabitacionRepository extends EntityRepository
{
	/** DADO EL TIPO Y CATEGORIA DE UNA HABITACION DEVUELVE EL NUMERO DE PERSONAS MAXIMO ADMITIDO **/
	public function obtener_ocupacion($tipo, $categoria)
	{
		$query = $this->getEntityManager()
			->createQuery('SELECT u FROM LIHotelBundle:OcupacionHabitacion u 
							WHERE u.tipoHabitacion = :tipo AND u.categoriaHabitacion = :categoria');
		$query->setParameter('tipo', $tipo);
		$query->setParameter('categoria', $categoria);		
		$result = $query->getResult();
		return $result;
	}
}
