<?php

namespace LI\Bundle\HotelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaRepository extends EntityRepository
{
	// OBTIENE LAS RESERVAS DE UN USUARIO DADO
	public function reservas_usuario($iduser){
		$query = $this->getEntityManager()
			->createQuery('SELECT u FROM LIHotelBundle:Reserva u WHERE u.cliente = :iduser');
		$query->setParameter('iduser', $iduser);
		$result = $query->getResult();
		return $result;
	}

	//DEVUELVE LAS RESERVAS DADA LA HABITACION
	public function reservas_de_la_habitacion($idhabitacion){
		$query = $this->getEntityManager()
			->createQuery('SELECT u FROM LIHotelBundle:Reserva u WHERE u.habitacion = :idhabitacion');
		$query->setParameter('idhabitacion', $idhabitacion);
		$result = $query->getResult();
		return $result;
	}

	//DEVUELVE LAS INSTANCIAS DE LAS HABITACIONES CUYA ESTADO RESERVA ES DISTINTO DE CANCELADA
	public function reservas_habitacion($idhabitacion){
		$query = $this->getEntityManager()
			->createQuery('SELECT u FROM LIHotelBundle:Reserva u WHERE u.habitacion = :idhabitacion AND u.estadoReserva != :estadoReserva');
		$query->setParameter('idhabitacion', $idhabitacion);
		$query->setParameter('estadoReserva', 'Cancelada');
		$result = $query->getResult();
		return $result;
	}

	//DADO EL CODIGO DE LA RESERVA VERIFICA SI EXISTE
	public function reservas_existe_codigo($codigo_reserva)
	{
		$query = $this->getEntityManager()
			->createQuery('SELECT u FROM LIHotelBundle:Reserva u WHERE u.codigoReserva = :codigo_reserva');
		$query->setParameter('codigo_reserva', $codigo_reserva);
		$result = $query->getResult();
		if (sizeof($result)>0) { return true; }else{ return false; }
	}

	//DADO EL CODIGO DEVUELVE LA RESERVA
	public function reservas_obtener_codigo($codigo_reserva)
	{
		$query = $this->getEntityManager()
			->createQuery('SELECT u FROM LIHotelBundle:Reserva u WHERE u.codigoReserva = :codigo_reserva');
		$query->setParameter('codigo_reserva', $codigo_reserva);
		$result = $query->getResult();
		return $result;
	}
}
