<?php

namespace LI\Bundle\HotelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoHabitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoHabitacionRepository extends EntityRepository
{
	public function precio_del_tipo($tipo){
		$query = $this->getEntityManager()
			->createQuery('SELECT u FROM LIHotelBundle:TipoHabitacion u WHERE u.nombre = :tipo');
		$query->setParameter('tipo', $tipo);
		$result = $query->getResult();
		return $result;
	}
}
