<?php

namespace LI\Bundle\HotelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRepository extends EntityRepository
{
	/* Devuelve entidades Tipo */
	public function habitaciones_tipo($tipo, $categoria){
		$query = $this->getEntityManager()
				->createQuery('SELECT u 
				FROM LIHotelBundle:Tipo u 
				WHERE u.tipoHabitacion = :tipo_id
				AND u.categoriaHabitacion = :categoria_id');
		$query->setParameter('tipo_id', $tipo);
		$query->setParameter('categoria_id', $categoria);
		$result = $query->getResult();
        
        return $result;
	}
}
