llamada:
    path:     /
    defaults: { _controller: "LIHotelBundle:Llamada:index" }

llamada_show:
    path:     /{id}/show
    defaults: { _controller: "LIHotelBundle:Llamada:show" }

llamada_new:
    path:     /new
    defaults: { _controller: "LIHotelBundle:Llamada:new" }

llamada_create:
    path:     /create
    defaults: { _controller: "LIHotelBundle:Llamada:create" }
    methods:  POST

llamada_edit:
    path:     /{id}/edit
    defaults: { _controller: "LIHotelBundle:Llamada:edit" }

llamada_update:
    path:     /{id}/update
    defaults: { _controller: "LIHotelBundle:Llamada:update" }
    methods:  [POST, PUT]

llamada_delete:
    path:     /{id}/delete
    defaults: { _controller: "LIHotelBundle:Llamada:delete" }
    methods:  [POST, DELETE]
