reserva:
    path:     /
    defaults: { _controller: "LIHotelBundle:Reserva:index" }

user_reserva:
    path:     /user
    defaults: { _controller: "LIHotelBundle:Reserva:indexuser" }

reserva_show:
    path:     /{id}/show
    defaults: { _controller: "LIHotelBundle:Reserva:show" }

user_reserva_show:
    path:     /{id}/user-show
    defaults: { _controller: "LIHotelBundle:Reserva:showuser" }

reserva_new:
    path:     /new
    defaults: { _controller: "LIHotelBundle:Reserva:new" }

user_reserva_new:
    path:     /user-new
    defaults: { _controller: "LIHotelBundle:Reserva:newuser" }

reserva_create:
    path:     /create
    defaults: { _controller: "LIHotelBundle:Reserva:create" }
    methods:  POST

reserva_edit:
    path:     /{id}/edit
    defaults: { _controller: "LIHotelBundle:Reserva:edit" }

user_reserva_edit:
    path:     /{id}/user-edit
    defaults: { _controller: "LIHotelBundle:Reserva:edituser" }

reserva_update:
    path:     /{id}/update
    defaults: { _controller: "LIHotelBundle:Reserva:update" }
    methods:  [POST, PUT]

reserva_delete:
    path:     /{id}/delete
    defaults: { _controller: "LIHotelBundle:Reserva:delete" }
    methods:  [POST, DELETE]
